import type { Metadata } from "next";
import "./globals.css";
import { Mplus1 } from "./fonts/Mplus1s";
import { LensGrotesk } from "./fonts/LensGrotesk";
import Header from "@/components/ui/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${LensGrotesk.variable} ${Mplus1.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
