name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Install pnpm
        run: npm install -g pnpm

      # Install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Prune the workspace (if using turbo repo)
      - name: Prune workspace
        run: pnpm turbo prune web-jp

      # Install dependencies again in the app directory
      - name: Install dependencies in app directory
        run: |
          cd out/apps/web-jp
          pnpm install

      # Build the project
      - name: Build the project
        run: |
          cd out/apps/web-jp
          pnpm build

      # Deploy the project to Azure
      - name: Build And Deploy
        id: builddeploy
        uses: azure/static-web-apps-deploy@latest
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_PEBBLE_0C23B9C00 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e. PR comments)
          action: "upload"
          app_location: "/out/apps/web-jp"  # Ensure this points to the correct build directory
          api_location: ""  # No API folder
          output_location: ""  # Optional, based on your build
          skip_app_build: true
        env:
          IS_STATIC_EXPORT: true
          SKIP_NPM_INSTALL: "true"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_PEBBLE_0C23B9C00 }}
          action: "close"
