name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  prune_and_build_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Prune, Build, and Deploy
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Install pnpm
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install pnpm
        run: npm install -g pnpm

      # Install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Prune the workspace
      - name: Prune workspace
        run: pnpm turbo prune apps/web-jp

      # Build the project
      - name: Build the project
        run: |
          cd out/full/apps/web-jp
          pnpm build

      # Deploy to Azure Static Web Apps
      - name: Deploy to Azure
        uses: azure/static-web-apps-deploy@latest
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_PEBBLE_0C23B9C00 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "out/full/apps/web-jp"
          output_location: "out/full/apps/web-jp/.next"
